version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          command: |
            echo $HELLO
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          command: |
            echo $TEST

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test
