version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2
    steps:
      - checkout
      - run: php -v
      - run: echo $TEST

workflows:
  version: 2
  workflow:
    jobs:
      - build:
         context: rename-test
