version: 2
default: &default
  working_directory: ~/ff-plus
  docker:
    - image: circleci/php:5.6.38-apache-jessie-node-browsers-legacy
jobs:
  build:
    <<: *default
    steps:
      - checkout
      - run:
          name: change hosts
          command: |-
            echo 127.0.0.1 ff-plus.local | sudo tee -a /etc/hosts
      - run: cat /etc/hosts
      - run: pwd
      # - run: sudo cp circle.conf /etc/apache2/sites-available/default.conf
      # - run: sudo a2enmod rewrite
      # - run: sudo service apache2 restart
      # - run: curl ff-plus.local

workflows:
  version: 2
  default:
    jobs:
      - build
