version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          command: |
            echo $HELLO

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          context: cheekit-dev-public
