version: 2
jobs:
  build:
    docker:
      - image: meetfrank/circleci-node-awsebcli
    steps:
      - checkout
      - run: sleep 300
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
