version: 2
jobs:
  build:
    docker:
      - image: meetfrank/circleci-node-awsebcli
    steps:
      - checkout

  build-another:
    docker:
      - image: meetfrank/circleci-node-awsebcli
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - approve:
          type: approval
          requires:
            - build
      - build-another:
          requires:
            - approve
